### ISSUE TITLE
Porting dateToRfc822 Filter to eleventy-plugin-rss

### ISSUE THREAD

**Issue by backlineint** [jeremenichelli/eleventy-xml-plugin#15]
Likely no action here, but wanted to give a heads up that I created the following PR https://github.com/11ty/eleventy-plugin-rss/pull/24 that adds dateToRfc822 (based on the work in this plugin) to eleventy-plugin-rss. Given the lack of activity here, I'm hoping that is ok, but if it isn't, let me know.

Thanks for the work on this plugin!

**Comment by kkgthb** [comment]
This would be useful, as I'm trying to play w/ a DIY podcast-building port from a Jekyll example.
