### ISSUE TITLE
Doesn't seem to be working?

### ISSUE THREAD

**Issue by cfjedimaster** [jeremenichelli/eleventy-xml-plugin#6]
Sorry for the vague title, but that's the best I can say. I installed the plugin and then tried to use it, but it doesn't seem to do anything. So for example:

```
<title>{{ post.data.title | xml_escape }} {{ "ray <a>link</a>" | 'xml_escape' }}</title>
```

When output, the tags in the hard coded string are not escaped as I'd expect.

**Comment by kaleb** [comment]
It seems to be correctly decoding entities but not the `<` and `>`.

**Comment by kaleb** [comment]
According to https://www.rubydoc.info/gems/jekyll/Jekyll%2FFilters%3Axml_escape the output is this:

```
xml_escape('foo "bar" <baz>')
# => "foo &quot;bar&quot; &lt;baz&gt;"
```

**Comment by sentience** [comment]
For anyone else being bitten by this, I've created a branch that you can install from GitHub, with this in your package.json:

```
  "devDependencies": {
    "@11ty/eleventy": "^1.0.0",
    "eleventy-xml-plugin": "github:sentience/eleventy-xml-plugin#dist"
  }
```

**Comment by jcubic** [comment]
The library is all wrong, it use [decode from html-entities](https://github.com/jeremenichelli/eleventy-xml-plugin/blob/master/src/escape-xml.js) instead of encode. So it unescape. Just ignore the library that is useless and use html-entities directly:

```javascript
const { encode } = require('html-entities');
module.exports = function(eleventyConfig) {
    // ... other config
    eleventyConfig.addFilter("xml_escape", function(str) {
        return encode(str, {level: 'xml'});
    });
};
```

THe library is only 4 lines of code that use obsolute version of html-entities anyway.

**Comment by jeremenichelli** [comment]
Sorry folks for not responding, I stepped away from open source for years. Just catching in, hope everyone got a way around it 🙏
